"""Type definitions for Trakt API."""

from .api_responses import (
    AnticipatedMovieWrapper,
    AnticipatedShowWrapper,
    CastMember,
    CheckinResponse,
    CommentResponse,
    CrewMember,
    DeviceCodeResponse,
    EpisodeResponse,
    FavoritedMovieWrapper,
    FavoritedShowWrapper,
    ListItemResponse,
    ListUserResponse,
    MovieResponse,
    PeopleResponse,
    PersonResponse,
    PlayedMovieWrapper,
    PlayedShowWrapper,
    SearchResult,
    SeasonResponse,
    SeasonStatsResponse,
    ShowResponse,
    StatsResponse,
    TokenResponse,
    TraktIdsDict,
    TraktRating,
    TranslationResponse,
    TrendingWrapper,
    UserResponse,
    UserWatchedEpisode,
    UserWatchedMovie,
    UserWatchedSeason,
    UserWatchedShow,
    WatchedMovieWrapper,
    WatchedShowWrapper,
)
from .common import (
    ErrorResponse,
    JSONValue,
    T,
    TraktHeaders,
    TRequest,
    TResponse,
)
from .ids import TraktIds
from .pagination import (
    PaginatedResponse,
    PaginationMetadata,
    PaginationParams,
)
from .protocols import (
    AuthClientProtocol,
    CheckinClientProtocol,
    MoviesClientProtocol,
    SearchClientProtocol,
    ShowsClientProtocol,
    UserClientProtocol,
)
from .sort import (
    EpisodeCommentSort,
    MovieCommentSort,
    SeasonCommentSort,
    ShowCommentSort,
)

__all__ = [
    # Anticipated Types
    "AnticipatedMovieWrapper",
    "AnticipatedShowWrapper",
    # Protocol Types
    "AuthClientProtocol",
    "CastMember",
    "CheckinClientProtocol",
    "CheckinResponse",
    "CommentResponse",
    "CrewMember",
    "DeviceCodeResponse",
    "EpisodeCommentSort",
    "EpisodeResponse",
    "ErrorResponse",
    "FavoritedMovieWrapper",
    "FavoritedShowWrapper",
    "JSONValue",
    "ListItemResponse",
    "ListUserResponse",
    "MovieCommentSort",
    "MovieResponse",
    "MoviesClientProtocol",
    # Pagination Types
    "PaginatedResponse",
    "PaginationMetadata",
    "PaginationParams",
    "PeopleResponse",
    "PersonResponse",
    "PlayedMovieWrapper",
    "PlayedShowWrapper",
    "SearchClientProtocol",
    "SearchResult",
    "SeasonCommentSort",
    "SeasonResponse",
    "SeasonStatsResponse",
    "ShowCommentSort",
    "ShowResponse",
    "ShowsClientProtocol",
    # Sort Types
    "StatsResponse",
    "T",
    "TRequest",
    "TResponse",
    "TokenResponse",
    "TraktHeaders",
    # API Response Types
    "TraktIds",
    "TraktIdsDict",
    "TraktRating",
    "TranslationResponse",
    "TrendingWrapper",
    "UserClientProtocol",
    "UserResponse",
    "UserWatchedEpisode",
    "UserWatchedMovie",
    "UserWatchedSeason",
    "UserWatchedShow",
    "WatchedMovieWrapper",
    "WatchedShowWrapper",
]
